name: Fetch RSS Feeds

on:
  schedule:
    - cron: '0 * * * *' # 每小时执行一次
  workflow_dispatch:

jobs:
  fetch-rss:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Fetch RSS data
        run: npm run fetch

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add output/rss.json
          git commit -m "Update RSS feed data"
          git push